// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PivotDb>>
abstract class PivotDb implements RustOpaqueInterface {
  List<LogEntry> get entries;

  String get filePath;

  set entries(List<LogEntry> entries);

  set filePath(String filePath);

  static Future<PivotDb> load({required String path}) =>
      RustLib.instance.api.crateApiSimplePivotDbLoad(path: path);

  Future<void> logTransition({
    required List<String> endedTasks,
    required List<String> startedTasks,
  });

  Future<void> save();
}

class LogEntry {
  final DateTime timestamp;
  final List<String> endedTasks;
  final List<String> startedTasks;

  const LogEntry({
    required this.timestamp,
    required this.endedTasks,
    required this.startedTasks,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^ endedTasks.hashCode ^ startedTasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          endedTasks == other.endedTasks &&
          startedTasks == other.startedTasks;
}
