// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PivotDb>>
abstract class PivotDb implements RustOpaqueInterface {
  List<LogEntry> get entries;

  String get filePath;

  set entries(List<LogEntry> entries);

  set filePath(String filePath);

  /// Converts the current database entries into a legacy string format.
  /// The format groups by date and represents transitions as:
  /// {ended_tasks} -{HHMM}-{started_tasks}
  Future<String> convertToLegacy();

  static Future<PivotDb> load({required String path}) =>
      RustLib.instance.api.crateApiSimplePivotDbLoad(path: path);

  Future<void> logTransition({
    required List<String> endedTasks,
    required List<String> startedTasks,
  });

  Future<void> save();
}

/// Represents a single moment in time when tasks transition.
///
/// This is the core data structure of the application. Instead of
/// tracking duration, it logs a "tick" where one or more tasks end,
/// and one or more tasks begin.
class LogEntry {
  /// The exact UTC timestamp of the transition.
  final DateTime timestamp;

  /// A list of tasks that were just completed. Can be empty.
  final List<String> endedTasks;

  /// A list of tasks that are starting now. Can be empty.
  final List<String> startedTasks;

  const LogEntry({
    required this.timestamp,
    required this.endedTasks,
    required this.startedTasks,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^ endedTasks.hashCode ^ startedTasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          endedTasks == other.endedTasks &&
          startedTasks == other.startedTasks;
}
